# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{seleniumrc_fc_webrat_mapper}
  s.version = "0.1.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Niall Mullally"]
  s.date = %q{2009-12-15}
  s.email = %q{niall@4l.ie}
  s.extra_rdoc_files = [
    "README.rdoc"
  ]
  s.files = [
    "MIT-LICENSE",
     "README.rdoc",
     "Rakefile",
     "VERSION",
     "install.rb",
     "lib/seleniumrc_fu_webrat_mapper.rb",
     "lib/seleniumrc_fu_webrat_mapper/core_extensions/string.rb",
     "lib/seleniumrc_fu_webrat_mapper/matchers.rb",
     "lib/seleniumrc_fu_webrat_mapper/methods.rb",
     "lib/seleniumrc_fu_webrat_mapper/selenium/matchers.rb",
     "lib/seleniumrc_fu_webrat_mapper/shared_matchers.rb",
     "seleniumrc_fc_webrat_mapper-0.1.0.gem",
     "seleniumrc_fc_webrat_mapper.gemspec",
     "test/matchers_test.rb",
     "test/methods_test.rb",
     "test/selenium_matchers_test.rb",
     "test/string_test.rb",
     "test/test_helper.rb"
  ]
  s.homepage = %q{http://github.com/Sidane/seleniumrc_fu_webrat_mapper}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.5}
  s.summary = %q{For simplifying migrating of Seleniumrc_fu Rails plugin tests to Webrat tests}
  s.test_files = [
    "test/matchers_test.rb",
     "test/methods_test.rb",
     "test/selenium_matchers_test.rb",
     "test/string_test.rb",
     "test/test_helper.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end

